version: '3'

services:
  web:
    build: .
    image: ctf-robot-signin:latest
    restart: unless-stopped
    # volumes:
    #   - ./static:/var/www/html
    environment:
      # - BIND_ADDR=0.0.0.0:80
      # - STATIC_PATH=/var/www/html
      - TZ=Asia/Shanghai
      - FLAG=flag{example_real_flag}
    ports:
      - "8000:80"
