name: Test

on:

  push:
  pull_request:

jobs:
  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup clippy
      id: setup-clippy
      run: rustup component add clippy

    - name: Cargo clippy checks
      run: cargo clippy --all-features --all-targets -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]

    steps:
    - uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: |
        rustup target add ${{ matrix.target }}
        cargo build --target ${{ matrix.target }} --release --bin web_server